### ISSUE TITLE
ETA for next release to npm?

### ISSUE THREAD

**Issue by justingrant** [aws/aws-sdk-js-crypto-helpers#175]
It's been 8 months since the last release of this repo's packages to the npm registry. When is the next released planned?

I'm asking because I've built a PR to fix various sourcemap problems with aws-amplify and along with fixes to that repo I also want to bump its other AWS dependencies like @aws-crypto to versions containing the sourcemaps fixes from #169 that was merged in this repo a few weeks ago.

**Comment by lavaleri** [comment]
Hi @justingrant

Thanks for the question, and sorry for the delay!

There isn't anything currently blocking a new release, so I will work to schedule one. I will update this ticket once I have an ETA.

**Comment by trivikr** [comment]
@lavaleri AFAICT `aws-sdk-js-crypto-helpers` looks stable for version `1.0.0` release.

AWS JavaScript SDK v3 is going to publish Release Candidate on 10/19, and we're close to GA. We would like to switch to `v1.0.0` of `aws-sdk-js-crypto-helpers` in our RC releases.
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1578

**Comment by trivikr** [comment]
> AWS JavaScript SDK v3 is going to publish Release Candidate on 10/19, and we're close to GA.

Update: The RC version of AWS JavaScript SDK v3 was published: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-rc.1

**Comment by justingrant** [comment]
Is there anything else holding up a release to npm of `aws-sdk-js-crypto-helpers`?  If not, when should we expect a new release? I'd really like to get my PR done soon for aws-amplify as every week that goes by means a more painful reworking it to catch up with more Amplify checkins.

**Comment by lavaleri** [comment]
We have completed the npm release of 1.0.0. Thanks for your patience!
