### ISSUE TITLE
Use lerna fixed versioning

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-crypto-helpers#184]
**Is your feature request related to a problem? Please describe.**

Reference: https://github.com/lerna/lerna#fixedlocked-mode-default

1. Currently the SDK create a new tag for each new version each subpackage. This results in having too many tags to maintain. 
1. Using independent versioning also adds some unnecessary complexity over the release system.
1. Most popular monorepos use fixed versioning, like [Lerna](https://github.com/lerna/lerna/blob/master/lerna.json), [Babel](https://github.com/babel/babel/blob/master/lerna.json)

**Describe the solution you'd like**

Move the fixed versioning.

**Additional context**
aws-sdk-js-v3 switched to fixed versioning with their release candidate in https://github.com/aws/aws-sdk-js-v3/issues/1248

**Comment by seebees** [comment]
This is a good argument. Thanks for the PRs.
