### ISSUE TITLE
Switch to yarn workspaces

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-crypto-helpers#23]
As per offline discussion, my suggestion is to switch to [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) so that there’s a single yarn.lock file in the root to view all dependencies.

Recommendation for:
* We at [aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3) been using lerna for couple of years now. We switched to yarn ~6 months ago, and have been very happy with it.
* About dependabot, example workshop code repo:
  * we didn’t use workspaces before, so dependabot used to create PR for each package http://bit.ly/2ZYS6M1
  * after moving to yarn workspaces, dependabot started updating dependencies globally http://bit.ly/2QTF26u

**Comment by rstormsf** [comment]
I'd say lerna is much better choice for handling big monorepos where each package is isolated from other packages in terms of dependencies. Having global dependencies for the whole project can provide negative results in the long term if the project grows in complexity.
