### ISSUE TITLE
Prefer "Squash and merge" while merging Pull Requests?

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-crypto-helpers#28]
I noticed that this project uses "Create a merge commit" while merging PRs.
This creates a merge commit, and all commits from PR (including experimental ones) are merged to master.

Commit history: https://github.com/aws/aws-sdk-js-crypto-helpers/commits/master

Merge commit and base commits for #26
![Screen Shot 2020-01-17 at 3 03 48 PM](https://user-images.githubusercontent.com/16024985/72652218-ace81a00-393a-11ea-9a35-e19ed4d801f7.png)

Mixed commits between #19 and #25 
![Screen Shot 2020-01-17 at 3 04 08 PM](https://user-images.githubusercontent.com/16024985/72652243-cee19c80-393a-11ea-8954-2f25ab287f69.png)

Suggestion: Do the following in settings https://github.com/aws/aws-sdk-js-crypto-helpers/settings
* Disable "Allow merge commits" and "Allow rebase merging"
* Only enable "Allow squash merging"

Squash and merge will create one commit per PR, keeping the history clean.
Squash merging is used in https://github.com/aws/aws-sdk-js-v3/commits/master

**Comment by trivikr** [comment]
Some discussions from Amazon Chime:

In [aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/), we squash almost all the times to keep the commit history clean.
If we need more info about specific commit, we visit PR associated with the commit and view its commits.

For example:
* commit: https://github.com/aws/aws-sdk-js-v3/commit/aca1bc07257296575c6aa3c132079edb2d281569
* PR (from commit msg): https://github.com/aws/aws-sdk-js-v3/pull/723
* Individual commits: https://github.com/aws/aws-sdk-js-v3/pull/723/commits

We use “rebase and merge” for rare PRs, where individual commits need to be preserved.
For example, PR which generates initial code for 17 clients was rebased and merged https://github.com/aws/aws-sdk-js-v3/pull/746

We use commitlint in CI and lint-staged to test for format of commit message in each commit https://github.com/aws/aws-sdk-js-v3/pull/239
For squashed commit msg, the maintainer ensures the PR is title is updated before merging.
We usually update the title as soon as context changes, and verify if title is incorrect before reviewing the PR

**Comment by seebees** [comment]
We are working on an auto-merge.
While most PR's should be squashed, not every one should.
Expressing this intent between the project and the requester is key.

At this time, I am using the `Require branches to be up to date before merging` setting in branch protection.
This should help with keeping the history linear if not perfectly clean.
