### ISSUE TITLE
Package Name needs to be updated in READMEs

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-crypto-helpers#3]
All the subpackages here has a name of `@aws/xxx` but the published packages' org name is `@aws-sdk`.

BTW: Can you all add github repository link to your package.json? It will be helpful to find the repo from NPM package page.

**Comment by mattsb42-aws** [comment]
> All the subpackages here has a name of @aws/xxx but the published packages' org name is @aws-sdk.

Correction: they should all be published under `@aws-crypto/`. The few I checked appear to be correct, but yes, the readme files need to be updated to match.

This is intentionally not `@aws-sdk/` because they are maintained separately by different people.

**Comment by AllanFly120** [comment]
Sorry I meant `@aws-crypto`
