### ISSUE TITLE
`aws-sdk/types@^3.1.0` dependency generates error TS2305 with `aws-sdk/*` since 3.54.1

### ISSUE THREAD

**Issue by KeithGillette** [aws/aws-sdk-js-crypto-helpers#337]
Per [`@aws-sdk` issue #3437](https://github.com/aws/aws-sdk-js-v3/issues/3437), I believe a PR incorporated into `@aws-sdk/*@3.54.1`, which [moved several types from `@aws-sdk/shared-ini-file-loader` into `@aws-sdk/types`](https://github.com/aws/aws-sdk-js-v3/commit/ad6890d9eb58da4c2e192a461f78a57a5fc53f75#diff-730b534a16f7d59b5c4d03738b32b569c424b97c3d165283eb2afe7ae2cd4ef6), generated an incompatibility with `aws-crypto` packages depending on `aws-sdk/types@^3.1.0`, resulting in error TS2305 when running `tsc` on a project with the default `tsconfig.json` `skipLibCheck: false`.

In testing with a project dependent upon `@aws-crypto/sha256-browser@2.0.1`, [forcing installation of `@aws-sdk/types@latest` prevents the TS2305 error](https://github.com/aws/aws-sdk-js-v3/issues/3437#issuecomment-1100686627). Can `@aws-crypto` packages be updated to a newer `@aws-sdk/types` compatible with the latest `@aws-sdk` releases?

**Comment by josecorella** [comment]
Hello @KeithGillette!

Thank you for bringing this to our attention; we have put out a fix and released it. You should be able to pick it up in the latest version of the @aws-crypto packages.
