### ISSUE TITLE
Release 3.x with dropped support for Internet Explorer and Node.js 12.x

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-crypto-helpers#472]
### Is your feature request related to a problem? Please describe.

Not a problem, but FYI that support for Internet Explorer and Node.js 12.x can be dropped

The support is already dropped by AWS SDK for JavaScript as follows:
* Internet Explorer:
  * May 2022: [Announcing the end of support for Internet Explorer 11 in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-internet-explorer-11-in-the-aws-sdk-for-javascript-v3/)
  * Oct 2022: https://github.com/aws/aws-sdk-js-v3/pull/4006
* Node.js 12.x:
  * May 2022: [Announcing the end of support for Node.js 12.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/)
  * Nov 2022: https://github.com/aws/aws-sdk-js-v3/pull/4123

### Describe the solution you'd like
Drop support for Node.js 12.x and Internet Explorer:
* Testing can be removed from Node.js 12 https://github.com/aws/aws-sdk-js-crypto-helpers/blob/dc83f76f9892fe205b601e3c8aeba779cb224ca6/.github/workflows/ci-unit-tests.yaml#L16
* And [engines](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines) field can be added in package.json to support only Node.js 14.x+
	* Example: https://github.com/aws/aws-sdk-js-v3/blob/d3ccee7cbe3a0cda64af32aff5a1485e3941daf9/clients/client-s3/package.json#L96-L98
* Code specific to IE11 can be removed.
    * Example: https://github.com/aws/aws-sdk-js-crypto-helpers/blob/45c50ffa3acc9e3bf4039ab59a0102e4d40455ec/packages/sha1-browser/src/crossPlatformSha1.ts#L14-L16

### Describe alternatives you've considered
Continue supporting Node.js 12.x and Internet Explorer

**Comment by justplaz** [comment]
Hello,

We have released versions 4.x and 5.x which remove Node12 and IE11: https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/CHANGELOG.md#breaking-changes.
