### ISSUE TITLE
update dependecy on tslib to latest version

### ISSUE THREAD

**Issue by kuhe** [aws/aws-sdk-js-crypto-helpers#481]
Having older tslib versions causes webpack duplication and node module nesting to occur. 

I noticed when I was bundling the AWS SDK JS v3 in webpack bundle analyzer as a size inspection.

Users can manually override with the following in webpack.config.js
```js
  resolve: {
    alias: {
      tslib: path.join(__dirname, "node_modules", "tslib"),
    },
  },
```

**Comment by AllanZhengYP** [comment]
@texastony Please prioritize this one. This greatly impacts the bundle size

**Comment by ShubhamChaturvedi7** [comment]
Fixed here: https://github.com/aws/aws-sdk-js-crypto-helpers/pull/735
