### ISSUE TITLE
Release 3.x with Checksum interface implementations

### ISSUE THREAD

**Issue by AndrewFossAWS** [aws/aws-sdk-js-crypto-helpers#485]
### Is your feature request related to a problem? Please describe.

Not a problem. The `Hash` interface in [`@aws-sdk/types`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/types) package is being deprecated and replaced by the new `Checksum` interface. (See [PR](https://github.com/aws/aws-sdk-js-v3/pull/4216) for the new Checksum interface)

Several `Hash` implementations e.g. `AwsCrc32`, `Sha256`, etc are currently used in the `aws-sdk-js-v3` repo. The `Checksum` work can not be proceeded unless they are updated to use `Checksum`.

### Describe the solution you'd like
 
* Update all the existing `Hash` implementations to use `Checksum` instead e.g. `AwsCrc32`, `Sha256`, etc
* Keep existing `update` method if it contains `encoding` to maintain backward compatibility. E.g.

```
export class Sha256 implements Checksum {
  private readonly hash: Hash;

  update(data: Uint8Array): void;
  update(data: SourceData, encoding?: "utf8" | "ascii" | "latin1"): void {
    this.hash.update(data, encoding);
  }

}
```

**Comment by trivikr** [comment]
This issue can be closed as https://github.com/aws/aws-sdk-js-crypto-helpers/pull/492 was released in v3.0.0
