### ISSUE TITLE
@aws-crypto/sha-256-universal README.md shows invalid import path

### ISSUE THREAD

**Issue by KeithGillette** [aws/aws-sdk-js-crypto-helpers#55]
The Usage example in the [`sha256-universal` package](https://github.com/aws/aws-sdk-js-crypto-helpers/tree/master/packages/sha256-universal) shows the following import path:

`import {Sha256} from '@aws-crypto/crypto-sha256-universal'`

However, when installing `@aws-crypto/sha256-universal@1.0.0-alpha.0`, no such directory is created in`node_modules` The library is under `node_modules/@aws-crypto/sha256-universal`.

**Comment by seebees** [comment]
Thanks, this should be a simple update.
