### ISSUE TITLE
Add Copyright Owner

### ISSUE THREAD

**Issue by dmarkowvw** [aws/aws-sdk-js-crypto-helpers#553]
Please fill in the 
`Copyright [yyyy] [name of copyright owner]`
in the appendix of the copyright notice. Otherwise it is difficult for enterprises to use this.

**Comment by seebees** [comment]
All files have the shortened copyright style

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

The date is not required.
It is easier to maintain the file without a date
because the date SHOULD be updated
every time the file is modified.
