### ISSUE TITLE
@aws-crypto/sha256-browser doesn't support ReactNative

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-crypto-helpers#79]
Background: https://github.com/aws/aws-sdk-js-v3/issues/929

Currently, `sha256-browser` package doesn't work if ReactNative users enable the debug mode. This is because the package falsly detect the RN environment as browser invironment and try to utilize the `Crypto.Subtle` class that doesn't exist in the environment.

If you don't have plan to support RN use case soon, it's better to document in the README to use `@aws-crypto/sha256-js` indead.

/cc @seebees

**Comment by seebees** [comment]
This is an issue, the SDK has worked around this with https://github.com/aws/aws-sdk-js-v3/pull/998 but the higher level question around ReeactNative is still open.

This really is an issue that should be on the ReactNative side,
but not everything is super clean cut.
