### ISSUE TITLE
ECCN classification

### ISSUE THREAD

**Issue by dkwakkel** [aws/aws-sdk-js-crypto-helpers#793]
Does crypto-js has an ECCN classification?
https://en.wikipedia.org/wiki/Export_Administration_Regulations

**Comment by lucasmcdonald3** [comment]
Hi @dkwakkel,

No, this package does not have an ECCN classification. This project is provided as open source and is not subject to the Export Administration Regulations (EAR). It qualifies as "published" as defined in § 734.7 of the EAR; therefore, ECCNs are not applicable.
