### ISSUE TITLE
Update GitHub repo link on npmjs

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-crypto-helpers#8]
**Describe the bug**
npmjs website of @aws-crypto packages links to [aws-javascript-crypto-helpers](https://github.com/aws/aws-javascript-crypto-helpers) repo which doesn't exist

**To Reproduce**
* Visit npmjs website of any @aws-crypto package (for example, [@aws-crypto/crc32](https://www.npmjs.com/package/@aws-crypto/crc32))
* Click on github link in the right sidebar, which links to [aws-javascript-crypto-helpers](https://github.com/aws/aws-javascript-crypto-helpers) repo which doesn't exist

**Expected behavior**
The github link in npmjs website links to [aws-sdk-js-crypto-helpers](https://github.com/aws/aws-sdk-js-crypto-helpers)

**Screenshots**
![aws-crypto:crc32](https://user-images.githubusercontent.com/16024985/68138578-aae6f100-fedd-11e9-8d43-e860e870bb80.png)

**Comment by trivikr** [comment]
We noticed this issue in dependabot PR https://github.com/aws/aws-sdk-js-v3/pull/436

**Comment by seebees** [comment]
Ok, simple to fix.

**Comment by trivikr** [comment]
Any update on this request?
The GitHub link on npmjs website is not updated yet https://www.npmjs.com/package/@aws-crypto/sha256-js

Do you have to create a new release?

**Comment by trivikr** [comment]
Fixed with 0.1.0-preview.3 release
